---
language: php

before_script:
  # Install required utilities
  - sudo apt-get install -y netstat

  # OS information
  - uname -a

  # Installed package information
  - dpkg --get-selections | grep -v deinstall

  # Running process information
  - ps aux | less

  # CPU information
  - cat /proc/cpuinfo

  # Memory information
  - cat /proc/meminfo
  - free -m

  # Network information
  - netstat -lntu

  # Disk information
  - df -h

script:
  - test -y
