---
language: python

before_script:
  - sudo apt-get update

  # OS information
  - uname -a

  # Installed package information
  - dpkg --get-selections | grep -v deinstall

  # Running process information
  - ps aux

  # CPU information
  - cat /proc/cpuinfo

  # Memory information
  - cat /proc/meminfo
  - free -m

  # Network information
  - netstat -lntu

  # Disk information
  - df -h

  # Install VirtualBox and Vagrant
  - sudo apt-get install dpkg-dev virtualbox-dkms
  - sudo dpkg -i https://dl.bintray.com/mitchellh/vagrant/vagrant_1.6.5_x86_64.deb
  - sudo apt-get install linux-headers-$(uname -r)
  - sudo dpkg-reconfigure virtualbox-dkms

  - vagrant -v
  - vboxmanage -v

script:
  - vagrant -v
  - vboxmanage -v

# https://keyholesoftware.com/2012/12/05/building_vagrant_boxes_with_veewee_on_travis/
